server:
  port: 8181
spring:
  cloud:
    config:
      server:
        git:
          uri: https://bitbucket.org/virtusa-hack/config-store
          username: nuwansamarasinghe100@gmail.com
          password: nuw2727888220
          search-paths: '*service*'

